### ISSUE TITLE
ndio / master may not have all migrations checked in

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#182]
After running ```python manage.py makemigrations``` the files in the ```migrations``` folder for each django app need to be checked in. Deployed machines then get ```python manage.py migrate``` after each pull. There appear to be migrations on ndio / master that aren't checked in (on ndio there are issues with ```backup_id``` not having a default value). 

@randalburns @Aeusman @kunallillaney

**Comment by kunallillaney** [comment]
@randalburns Did you check in the migrations for the NDChannel thing you added for Greg?
