### ISSUE TITLE
imagesize actually means image_bounds (??)

### ISSUE THREAD

**Issue by j6k4m8** [neurodata/ndstore#186]
Consider [`bock11`](http://openconnecto.me/ocp/ca/bock11/info/):

```json
"imagesize": {
    "0": [
        135424, 
        119808, 
        4156
    ], 
```

These are the 'furthest' available coordinates, but they're not really the image size, which would really be `imagesize[d] - offset[d]` for `d` ∈ [0..3], unless I'm mistaken. I think this is a design question for @kunallillaney?

@jovo tagged for fun GitHub notifications!

**Comment by kunallillaney** [comment]
@j6k4m8 Yes this is correct.

The way we treat imagesize is the entire ROI of the data. It acts as a better translation for the people who own the data as they don't have to deal with remembering a different set of co-ordinate system.

**Comment by jovo** [comment]
@kunallillaney when we discussed this, i think we concluded that image size was correct, but some of the data were incorrect? in that case, are the data fixed and we can close this?

**Comment by jovo** [comment]
@kunallillaney re-open if i'm incorrect.
