### ISSUE TITLE
Migrate stats service to microns

### ISSUE THREAD

**Issue by kunallillaney** [neurodata/ndstore#208]
@alexbaden I merged the microns branch with the current master. I did replace some names in the stats service for the new branch but did not get all. Can you please pull merge microns with ab-histogram(don't think there will be any conflict here) and change the names in your service.

**Comment by alexbaden** [comment]
Stats service now works in microns (see https://github.com/neurodata/ndstore/commit/ea3b9e3fdd1d2645406df1a1818cecb2a8d20eae)
