### ISSUE TITLE
AutoIngest Better

### ISSUE THREAD

**Issue by Aeusman** [neurodata/ndstore#214]
- [x] Dataset -> {json}
- [x] Project -> {json}
- [x] channel {   }
- [x] success (with better explanation after)

**Comment by kunallillaney** [comment]
@Aeusman This is now in master. Confirm and close issue when you get a chance.

**Comment by Aeusman** [comment]
Import error on jsonspec.validators in ocpcaschema.py after clean install, can be seen here: http://ec2-54-201-19-176.us-west-2.compute.amazonaws.com/ocp/accounts/login/

**Comment by Aeusman** [comment]
@Self Resolved
