### ISSUE TITLE
load testing on DSPs

### ISSUE THREAD

**Issue by willgray** [neurodata/ndstore#216]
At long last, I have a (cube aligned) script for pulling down data from neurodata in a parallel fashion.  

I am excited and ready to load test.  Did some initial experiments against dsp062 and things seem to time out pretty fast.  Can you recommend a volume size to grab (right now I'm trying 5 readers each pulling 5120x5120x16 (~400MB) with no success.  (My earlier experiments had 10-20 threads and might have killed us - not sure because I don't have access to the logs, but DSP062 is still up.)

Much smaller test volumes work - we want 5000 1GB cubes for this experiment, more or less. 

@kunallillaney - can you propose some test runs and I'll execute and get back to you with timing/results?  

When the new DSP is ready, I can shift there, although curious to measure performance here as well.

@jovo @randalburns @alexbaden

**Comment by jovo** [comment]
@willgray this is great!
please post ilnk to code that you are using to load test.

**Comment by willgray** [comment]
Sure thing.  This is code on marcc, but changing the python path at the top should make this locally runable - takes one argument, which helps set z start slice.

We will continue to prettify and add options, but you get the idea.

~~~
#!/cm/shared/apps/anaconda/2.7.10/bin/python

import ndio.remote.neurodata as neurodata
import numpy as np
import argparse 

parser = argparse.ArgumentParser()
parser.add_argument('zinc',action='store',type=int,help='Increment on the base zslice')
result = parser.parse_args() 

zmin = 2917 + result.zinc * 16
zmax = zmin + 16 

nd = neurodata()
bock11_subvol = nd.get_cutout('bock11', 'image', 30720, 35840, 30720, 35840, zmin, zmax, resolution=1)
with open('data_out/bock11_subvol_{}-{}.np'.format(zmin, zmax), 'wb') as f:
	bock11_subvol.tofile(f)

print "Downloaded bock11 {} to {} (dims: {})".format(zmin, zmax, bock11_subvol.shape)

~~~

**Comment by kunallillaney** [comment]
So I need the latest ndio to run this right?

**Comment by willgray** [comment]
I pulled from master because we don't have pip easily accessible on marcc...but this doesn't use any recent stuff afaict.

This isn't doing any chunking - just a straight call.  Thanks for jumping right in!  Hopefully we can learn a lot now that I **finally** gave you test cases!

**Comment by kunallillaney** [comment]
Well @jovo has other stuff he needs from me so I am looking at this casually. Will look at more detail later.

**Comment by jovo** [comment]
right.
@willgray kunal is benchmarking the S3 stuff, which i expect to go into the paper.
the benchmarking of DSPs will be an important internal QC check, that i'm very excited to delve into *after* we finalize initial figure draft for the manuscript.

**Comment by willgray** [comment]
yah - the main goal here is a workable way to do our at scale run, vs. quantifying backend performance.

fwiw, a modified version of this script might be a nice test on s3 - I expect the use case "I want a GB of data to do something with" is a pretty vanilla real world request that might be nice to get timing on.  But I humbly defer to you guys.  :)

**Comment by jovo** [comment]
kunal wrote this: https://github.com/neurodata/ndtilecache/tree/kunal-devel/test

**Comment by kunallillaney** [comment]
@jovo Yeah but that is for the ndtilecache. I have to write one similar for ndstore.

**Comment by jovo** [comment]
right, i just thought they'd like to see what you have already.

On Tue, Feb 16, 2016 at 10:38 PM, Kunal Lillaney <notifications@github.com>
wrote:

> @jovo <https://github.com/jovo> Yeah but that is for the ndtilecache. I
> have to write one similar for ndstore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndstore/issues/216#issuecomment-185001797>.
>



-- 
the glass is all full:  half water, half air.
neurodata.io

**Comment by willgray** [comment]
Cool - so the preliminary tests we ran last night showed that with 5 readers we could do 4096x4096x16 downloads in about 2 minutes.  These blocks are still a little small for CV (250MB vs. 1-5GB is more ideal).  But we can chunk and make it work.

Interestingly, more readers seems to not increase overall throughput, although we're still gathering those numbers for formally  With more than about 10 readers, we start to time out.  ndio (@j6k4m8) has a chunking feature that may or may not help with building bigger blocks from smaller requests.

These speeds still seem slow to me based on historical runs and capability (I extrapolate a data rate of about 1TB/day download of image data only).  Any thoughts?

If people have specific test suggestions, I can run those and perhaps organize the results in a table.  Note that these runs are on dsp062, so we are competing for traffic with everyone else.

**Comment by jovo** [comment]
reproducible science

**Comment by willgray** [comment]
So for MARCC we submit via slurm - and get timings via email.  Open to better answers.  Single threaded, the code and results are as follows:

```
import ndio.remote.neurodata as neurodata
import numpy as np
import argparse 
import time

start = time.time()

#parser = argparse.ArgumentParser()
#parser.add_argument('zinc',action='store',type=int,help='Increment on the base zslice')
#result = parser.parse_args() 

i = 1

zmin = 2917 + i * 16
zmax = zmin + 16 

nd = neurodata()
bock11_subvol = nd.get_cutout('bock11', 'image', 30720, 35840, 30720, 35840, zmin, zmax, resolution=1)
with open('bock11_subvol_{}-{}.np'.format(zmin, zmax), 'wb') as f:
    bock11_subvol.tofile(f)

print "Downloaded bock11 {} to {} (dims: {})".format(zmin, zmax, bock11_subvol.shape)
print "Time Elapsed:" + str(time.time()-start)
```
```
Downloaded bock11 2933 to 2949 (dims: (16, 5120, 5120))
Time Elapsed:177.924670219
```

**What should I use to demonstrate multithreaded locally?  @randalburns @kunallillaney - the use case here is to retrieve 5TB of data in 1GB chunks.  What's the best read pattern?  I'm compute bound, so would like to have a few hundred compute cores active, but don't want to overwhelm the DSPs.  We don't have client side throttling set up on MARCC.**

A dumb way to do this is to pull down all 5TB with 5 readers and then operate completely on local hdf5 files.  But that scraping the db seems like a poor demonstration of our capabilities.  Thoughts?  Happy to talk in person or via this issue.

**Comment by jovo** [comment]
@willgray - this is perfect

@kunallillaney - maybe we can discuss after minihack?

On Thu, Feb 18, 2016 at 9:46 AM, William Gray <notifications@github.com>
wrote:

> So for MARCC we submit via slurm - and get timings via email. Open to
> better answers. Single threaded, the code and results are as follows:
>
> import ndio.remote.neurodata as neurodata
> import numpy as np
> import argparse
> import time
>
> start = time.time()
>
> #parser = argparse.ArgumentParser()
> #parser.add_argument('zinc',action='store',type=int,help='Increment on the base zslice')
> #result = parser.parse_args()
>
> i = 1
>
> zmin = 2917 + i * 16
> zmax = zmin + 16
>
> nd = neurodata()
> bock11_subvol = nd.get_cutout('bock11', 'image', 30720, 35840, 30720, 35840, zmin, zmax, resolution=1)
> with open('bock11_subvol_{}-{}.np'.format(zmin, zmax), 'wb') as f:
>     bock11_subvol.tofile(f)
>
> print "Downloaded bock11 {} to {} (dims: {})".format(zmin, zmax, bock11_subvol.shape)
> print "Time Elapsed:" + str(time.time()-start)
>
> Downloaded bock11 2933 to 2949 (dims: (16, 5120, 5120))
> Time Elapsed:177.924670219
>
> *What should I use to demonstrate multithreaded locally? @randalburns
> <https://github.com/randalburns> @kunallillaney
> <https://github.com/kunallillaney> - the use case here is to retrieve 5TB
> of data in 1GB chunks. What's the best read pattern? I'm compute bound, so
> would like to have a few hundred compute cores active, but don't want to
> overwhelm the DSPs. We don't have client side throttling set up on MARCC.*
>
> A dumb way to do this is to pull down all 5TB with 5 readers and then
> operate completely on local hdf5 files. But that scraping the db seems like
> a poor demonstration of our capabilities. Thoughts? Happy to talk in person
> or via this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndstore/issues/216#issuecomment-185751377>.
>



-- 
the glass is all full:  half water, half air.
neurodata.io

**Comment by willgray** [comment]
We seem like we have a plan for reading on MARCC pending some new ndio features.  Closing for now.
