### ISSUE TITLE
No module named jsonspec.validators

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#221]
I get that import error when I pull the latest master. What module am I missing? 

In the future, we should make a new release when dependencies change. It's helpful to those running the software.

@jovo @randalburns @kunallillaney

**Comment by j6k4m8** [comment]
I think it's `json-spec`, may be mistaken...

**Comment by alexbaden** [comment]
Thanks, Jordan.

**Comment by kunallillaney** [comment]
We now have a neurodata_install.sh which you can use to install everything from scratch and takes care of missing packages.

**Comment by jovo** [comment]
that is amazing! we should celebrate!
when are we starting ice cream celebrations again??

On Tue, Apr 26, 2016 at 10:48 PM, Kunal Lillaney <notifications@github.com>
wrote:

> We now have a neurodata_install.sh which you can use to install everything
> from scratch and takes care of missing packages.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndstore/issues/221#issuecomment-214954553>
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
