### ISSUE TITLE
set up AWS account "correctly"

### ISSUE THREAD

**Issue by jovo** [neurodata/ndstore#224]
this is perhaps @jovo task, but requires instructions at least from @gkiar @alexbaden @kunallillaney 

note: it will be my top priority next week.

**Comment by kunallillaney** [comment]
@jovo we now have a s3neurodata which hosts out s3 public bucket.

**Comment by jovo** [comment]
who is paying?

On Tue, Mar 8, 2016 at 3:28 PM, Kunal Lillaney <notifications@github.com>
wrote:

> @jovo <https://github.com/jovo> we now have a s3neurodata which hosts out
> s3 public bucket.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndstore/issues/224#issuecomment-193954785>.
>



-- 
the glass is all full:  half water, half air.
neurodata.io

**Comment by kunallillaney** [comment]
Currently this is setup with randal's AWS account(@alexbaden knows more). We can take the other discussion(the email you sent out) offline.

**Comment by jovo** [comment]
ok, not sure what you mean, but let's make sure it is being charged the
right place?

On Tue, Mar 8, 2016 at 3:58 PM, Kunal Lillaney <notifications@github.com>
wrote:

> Currently this is setup with randal's AWS account(@alexbaden
> <https://github.com/alexbaden> knows more). We can take the other
> discussion(the email you sent out) offline.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndstore/issues/224#issuecomment-193963848>.
>



-- 
the glass is all full:  half water, half air.
neurodata.io
