### ISSUE TITLE
JsonAnn service for microns is broken

### ISSUE THREAD

**Issue by kunallillaney** [neurodata/ndstore#230]
The jsonann tests don't pass. I have commented them out for now.

**Comment by alexbaden** [comment]
Yeah, the service will need to be refactored around the new RAMON. In fact, we can probably get rid of jsonann entirely and just use annotation.py. I will look into this -- do you have any objection to accepting a JSON post to the same URL for creating annotations? (i.e /nd/<<id>>/json responds to both GET and POST).

@randalburns

**Comment by kunallillaney** [comment]
Sounds good. Should be fine.

**Comment by alexbaden** [comment]
The GET interface has been fixed, and tests pass. https://github.com/neurodata/ndstore/commit/6c4c9da3d7aeba0f24467f7ec152b8b530bb9e16 

I'm going to make a separate issue for all RAMON related JSON discussion.
