### ISSUE TITLE
lims server enabled flag does the opposite

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#235]
In `metadatadict`, the if statement checks for `LIMS_SERVER_ENABLED` and returns a blank dictionary if the setting is yes:
```
def metadatadict( proj ):
  """Metadata Info"""
  if settings.LIMS_SERVER_ENABLED:
    return {}
```

Seems like it should be the opposite from the way the variable is worded? 

```
118 def metadatadict( proj ):
119   """Metadata Info"""
120   if settings.LIMS_SERVER_ENABLED is False:
121     return {}
122   else:
```

**Comment by kunallillaney** [comment]
My bad will fix it asap.

**Comment by kunallillaney** [comment]
@alexbaden Do you want this fixed in master as well? I can do that and it would simple.

**Comment by alexbaden** [comment]
Thanks! I think I'm 100% microns from here on out. It seems to not be causing any problems on my old branch install on brainviz or on my other installs, so I think it's fine to leave it as it in current master -- but up to you.
