### ISSUE TITLE
channel_idx0 table and channel_res0_index table 

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#243]
Need to pick one of `channel_idx0` or `channel_res0_index` -- not both 

From @randalburns

**Comment by kunallillaney** [comment]
@randalburns You are confusing the purposes of both those tables. One is for the S3index in mysql.

**Comment by alexbaden** [comment]
@randalburns says: it would be helpful if it was named extindex or s3index so as not to confuse the two.
