### ISSUE TITLE
public vs. private

### ISSUE THREAD

**Issue by jovo** [neurodata/ndstore#247]
in speaking with ailey and others, the word "public" is confusing to people, because we actually mean "secret", so rather than calling things "public" vs. "private", perhaps we should call them "public" and "secret"?  
so, ailey has to give us her *secret* url, not her *public* url.

thoughts?

@j6k4m8 @kunallillaney @alexbaden @randalburns

**Comment by kunallillaney** [comment]
@jovo For the purpose it is the public URL since that data has to be publicly accessible. We can call it the secretly publicly accessible URL if you like.

**Comment by jovo** [comment]
dropbox doesn't call links that are shared "public", neither does gdrive.  
gdrive says, under "sharing"

"Link to share (only accessible by collaborators)"

dropbox says:

"Who can view this?	
- [ ] Anyone with the link
- [ ] Only people with the password
"
i don't see why we have to say public if they don't?

gdrive actually has 3 options:

- public
- shared with collaborators
- private

we only have the first two.
