### ISSUE TITLE
'Unknown exception in getCutout. No module named redis'

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#248]
`pip install redis` didn't seem to do the trick. All URLs throw this error.

**Comment by kunallillaney** [comment]
I don't know what you are doing but pip install redis exists both on OSX and Ubuntu. I just checked again and all tests for me pass locally. Here is the link to the pip package https://pypi.python.org/pypi/redis

**Comment by alexbaden** [comment]
```

(ocp)alex@brainviz1:~/ndstore/test$ pip freeze | grep redis

*redis*==2.10.5

```

http://brainviz1.cs.jhu.edu/microns/nd/sd/collman15/DAPI1st/xy/2/400,500/400,500/55/


I think you have a brainviz login. Can you take a look?
`/var/www/ocp/ndstore/`

**Comment by kunallillaney** [comment]
It works fine. You were running your tests on the nginx web-server without restarting uwsgi. It works on the django server.

**Comment by alexbaden** [comment]
Wrong virtualenv. I installed it in the correct one and rebooted uwsgi --
all good now. Maybe I should go to bed...

Thanks for looking!
