### ISSUE TITLE
adding a version to projinfo

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#250]
There are some features in microns (maxproj, synaptograms, soon-to-be-RAMON-json) that won't ever be in current master. It would be great if NDV could check a field in projinfo that gives the version of ndstore currently serving that projinfo page. Ideally, this version would be updated automatically each time ndstore was updated (and not be tied to individual projects, like schema version). That way, I could say `if version > 1.0 ? maxproject : nomaxproject`. 

There is currently a version in projinfo, but that seems to be schema version, not ndstore version. 

Thoughts? @jovo @randalburns @kunallillaney

**Comment by jovo** [comment]
i'm fine with that.

On Mon, Mar 21, 2016 at 1:13 AM, Alex Baden <notifications@github.com>
wrote:

> There are some features in microns (maxproj, synaptograms,
> soon-to-be-RAMON-json) that won't ever be in current master. It would be
> great if NDV could check a field in projinfo that gives the version of
> ndstore currently serving that projinfo page. Ideally, this version would
> be updated automatically each time ndstore was updated (and not be tied to
> individual projects, like schema version). That way, I could say if
> version > 1.0 ? maxproject : nomaxproject.
>
> There is currently a version in projinfo, but that seems to be schema
> version, not ndstore version.
>
> Thoughts? @jovo <https://github.com/jovo> @randalburns
> <https://github.com/randalburns> @kunallillaney
> <https://github.com/kunallillaney>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndstore/issues/250>
>



-- 
the glass is all full:  half water, half air.
neurodata.io

**Comment by kunallillaney** [comment]
This is now done in the microns branch and will appear in the project.
"project": {
        "description": "", 
        "name": "hildebrand15", 
        "ndstore_version": "0.7", 
        "s3backend": 1, 
        "schema_version": "0.7"
    }

**Comment by jovo** [comment]
which token is on the cloud such that i can play with the RESTful calls
from AWS?

On Tue, Apr 26, 2016 at 10:47 PM, Kunal Lillaney <notifications@github.com>
wrote:

> Closed #250 <https://github.com/neurodata/ndstore/issues/250>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndstore/issues/250#event-642356993>
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by kunallillaney** [comment]
currently kasthuri11 and hildebrand15 on cloud.neurodata.io. The machine ingest jobs for you and does not have the current version of microns.

**Comment by jovo** [comment]
thanks

On Tue, Apr 26, 2016 at 10:58 PM, Kunal Lillaney <notifications@github.com>
wrote:

> currently kasthuri11 and hildebrand15 on cloud.neurodata.io. The machine
> ingest jobs for you and does not have the current version of microns.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndstore/issues/250#issuecomment-214956226>
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
