### ISSUE TITLE
Docs say genHist, command recodgnized: genhist

### ISSUE THREAD

**Issue by Aeusman** [neurodata/ndstore#255]
http://openconnecto.me/ocp/stats/codeneurochallenge0000/tifs/genHist/  -  fails with 404
http://openconnecto.me/ocp/stats/codeneurochallenge0000/tifs/genhist/  -  works
Docs say genHist, should I change to be genhist?
@alexbaden

**Comment by alexbaden** [comment]
You're absolutely right. Can you fix in docs? I'm not entirely clear on which branch the current docs are from. Thanks!!

**Comment by Aeusman** [comment]
No worries! I'll make a pull request for it on master.
