### ISSUE TITLE
overlay of X channels

### ISSUE THREAD

**Issue by jovo** [neurodata/ndstore#257]
if we want to make a single image that sums over k channels, say, all 5 excitatory postsynaptic marker types, can we do that?

@kunallillaney @randalburns @MrAE

**Comment by j6k4m8** [comment]
I think @willgray has some experience with this?

**Comment by willgray** [comment]
Hmmm - you mean in ndviz?  Fairly trivial to do programmatically client side - guessing you mean server side as a dynamic render (or even on a request basis)?

If client side, lemme know.

**Comment by kunallillaney** [comment]
@jovo not in ndstore maybe in ndviz.

**Comment by jovo** [comment]
i don't much care where.
but, for example, if there are 6 excitatory channels in an AT dataset, i'd want to merge them all, and then only have to load 1 image (rather than 6).  
i would do the same for the 6 inhibitory channels.

the reason is really speed, so i think i'd want it to happen on the backend, like i could make an ndviz project that has that property, and come back and look at it when it is ready.

**Comment by kunallillaney** [comment]
@jovo I think this will now happen in ndviz because @alexbaden is working on this with OpenGL.

**Comment by jovo** [comment]
cool

**Comment by jovo** [comment]
shall we make a new "feature request" issue?

**Comment by kunallillaney** [comment]
@jovo Sure you can do so in Ndviz, since this is relevant there.
