### ISSUE TITLE
auto ingest generatejson failed 

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#265]
```
(ocp)abaden@Alexs-MBP-3:~/Projects/Research/cookingest$ python generatejson.py 
Traceback (most recent call last):
  File "generatejson.py", line 21, in <module>
    import ndio.remote.ndingest as NI
ImportError: No module named ndingest
```

I followed the instructions here: http://docs.neurodata.io/ndstore/sphinx/ingesting.html but I seem to be missing something. Do I need a different version of ndio?

**Comment by Aeusman** [comment]
So it looks like @j6k4m8 hasn't rolled the latest into a 1.0.1, I'll poke him about it

**Comment by j6k4m8** [comment]
We're on a monthly rollout cycle, scheduled to roll to `1.1.0` on Sunday (first day of the month) if everything is stable.

**Comment by Aeusman** [comment]
Ah, nice, my understanding was flawed then, I thought the release cycle was bi-monthly :) Thanks!

**Comment by alexbaden** [comment]
Got it. I followed Jordan's instructions and am now running the ndio from the master branch in the repo. 

But, I'm still getting an error (though a new one this time):
```
Traceback (most recent call last):
  File "generatejson.py", line 87, in <module>
    main()
  File "generatejson.py", line 84, in main
    ni.post_data(SITE_HOST)
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/ndio/remote/ndingest.py", line 517, in post_data
    raise OSError("Error opening file")
OSError: Error opening file
```

I'm using the generatejson from the docs: https://github.com/neurodata/ndstore/blob/master/ingest/autoingest/generatejson.py

**Comment by kunallillaney** [comment]
@alexbaden Did this not work? If not let's resolve this with @Aeusman.

**Comment by alexbaden** [comment]
No, I ended up writing an ingest script instead. I attached my `generatejson.py` script, but the data has already been ingested using those parameters, so you will want to try slightly different ones. 

It turned out that the size of the tif image was different than the size of the catmaid stack (the catmaid stack was bigger to keep powers of 2). I forget exactly what the image was, but it was something like 6500 x 4500 instead of 65xx by 45xx. You can find out in the cook16 projinfo. 

[generatejson.py.zip](https://github.com/neurodata/ndstore/files/243709/generatejson.py.zip)

**Comment by Aeusman** [comment]
Figured out the problem, generatejson in ndstore was incorrectly passing a parameter in post_data(), usage has been changed. I've created a pull request to fix @kunallillaney
