### ISSUE TITLE
ndhist

### ISSUE THREAD

**Issue by jovo** [neurodata/ndstore#281]
can we discuss the pro's and con's of leaving the 'stats' module within ndstore, vs. making it its own repo?

#### pro's

- keeps things more modular
- is an example "plug-in" that in theory, other people could contribute as well
- it makes the ndpaper and probably the ndviz/ndtilecache papers a bit cleaner.

#### con's

- it does not work on its own (but this is true of all plug-ins)
- it will take some effort to move it.

@kunallillaney @randalburns @alexbaden thoughts?

**Comment by alexbaden** [comment]
I'm fine with the idea. 

There is a snag, which is the histograms are stored in the ocpuser / nduser models file. So, we would have to decouple the histograms from the backend metadata. But the only advantage to the coupling, at the moment anyway, is that deleting a channel will also delete its associated histogram (in theory, anyway -- in fact, this may not be true and if so would be a bug). 

I also suspect the timeline for doing this is > 1 month. Even just porting the stats service to a django app inside ndstore is work. And if we're going to separate it, there might be some advantages to running it as a more standalone micro-service.

**Comment by jovo** [comment]
oh > 1 month is a lot.  ok, let's punt until after writing the papers :)
eg, we could write a conference paper later on micro-services, with this being the prime example.
