### ISSUE TITLE
ndingest jupyter notebook

### ISSUE THREAD

**Issue by jovo** [neurodata/ndstore#282]
@Aeusman could you make a jupyter notebook demo'ing ndingest?
i realize this will require modifying the ndingest function somewhat
(ie, take a variable number of inputs or something).
if it needs to be a whole new function, that's ok too.

@kunallillaney

**Comment by Aeusman** [comment]
https://github.com/neurodata/ndio-demos/blob/AddINgest/Archive/Getting%20Started/Auto-Ingesting%20A%20Volume.ipynb

I made this a while back, but it looks like for whatever reason it was not merged in. For now I've left the variable values as their names to provide clarity as ndingest relates to the data model, but if you want me to do it differently let me know and I can change it.

**Comment by jovo** [comment]
that's great!
but it wouldn't work, because none of the variables have been specified.
can you make an example that would work,
and then discuss with will/jordan what you need to do to make a pull
request?


On Tuesday, June 7, 2016, Alex Eusman <notifications@github.com> wrote:

>
> https://github.com/neurodata/ndio-demos/blob/AddINgest/Archive/Getting%20Started/Auto-Ingesting%20A%20Volume.ipynb
>
> I made this a while back, but it looks like for whatever reason it was not
> merged in. For now I've left the variable values as their names to provide
> clarity as ndingest relates to the data model, but if you want me to do it
> differently let me know and I can change it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurodata/ndstore/issues/282#issuecomment-224350626>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACjctLVRrQ7veeYtaGCMIy18z3o8-Tkks5qJafbgaJpZM4Ivu7p>
> .
>


-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by kunallillaney** [comment]
@Aeusman claims done.
