### ISSUE TITLE
blosc error on mac os x 

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#292]
Can't run the dev server on OS X... some sort of blosc related error.

```
dlopen(/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/blosc/blosc_extension.so, 2): Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6resizeEmc
  Referenced from: /Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/blosc/blosc_extension.so
  Expected in: flat namespace
 in /Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/blosc/blosc_extension.so
```

I have `blosc==1.3.2` installed in my virtualenv. I think this is a new problem (meaning, I haven't seen it before with microns). Anyone encountered before? Any ideas? It seems like I don't have some sort of blosc library installed?

**Comment by j6k4m8** [comment]
I encounter this problem sometimes when I accidentally get a compiled version of blosc. How did you install blosc? May be worth (1) reinstalling, or (2) installing from another source. I think there's a homebrew tap available (not in standard brew, note)

pip installing is *not* sufficient, if I remember correctly. I think it's installing linux-compiled C binaries which break on OS X. It's possible this is the same thing @willgray got recently..?

**Comment by willgray** [comment]
I use version 1.2.0 I think.  It's obnoxious to remember, but seems to solve the problem.

**Comment by willgray** [comment]
note that this is just for ndio functionality, so possibly there are other use cases in ndstore that I haven't seen...

**Comment by alexbaden** [comment]
Resolved by ensuring my compilers were consistent and running:

```
pip install --force-reinstall --upgrade --no-cache-dir --compile blosc
```

I don't _believe_ you need anything other than the python blosc package to run on Mac OS X. However, I did compile the c-blosc library from source and install it in `/usr/local`... so maybe that had something to do with the fix. 

Wish apple would ditch clang and use gcc like the rest of us. Part of the problem might have been my C compiler was gcc but my CXX compiler was clang. Anyway, adding all those flags to pip usually cleans things up. Maybe we should add this to an FAQ or something similar on the docs page? @jovo?

**Comment by jovo** [comment]
perhaps the install docs should specify the OS for which we've tested and confirmed that it works (if it does not already).  i don't think we care much if people can't install ndstore on OSX, do we?

**Comment by alexbaden** [comment]
I think being able to develop locally on macOS is great, and we should tell people and support people to the fullest extent possible.

**Comment by jovo** [comment]
develop = download data, or run ndstore?

On Sun, Jun 19, 2016 at 1:14 PM, Alex Baden <notifications@github.com>
wrote:

> I think being able to develop locally on macOS is great, and we should
> tell people and support people to the fullest extent possible.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurodata/ndstore/issues/292#issuecomment-227008768>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACjcqQQXoK_HTIgJgcSFqX_2JhX3lOiks5qNXjkgaJpZM4I39B9>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by alexbaden** [comment]
Run ndstore locally to develop "plugins" (e.g. statistics). There are a bunch of different teams doing different things. If our software is the easiest to use, they'll start forking us instead of writing their own stuff from scratch.

**Comment by jovo** [comment]
would be nice.
we would need a human to do it.
you guys are already committed afaict,
so maybe when eric/somebody joins...

On Sun, Jun 19, 2016 at 2:41 PM, Alex Baden <notifications@github.com>
wrote:

> Run ndstore locally to develop "plugins" (e.g. statistics). There are a
> bunch of different teams doing different things. If our software is the
> easiest to use, they'll start forking us instead of writing their own stuff
> from scratch.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurodata/ndstore/issues/292#issuecomment-227013185>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACjcgcJ-yWb1DaUYM1jg7wxMNwExV_iks5qNY1LgaJpZM4I39B9>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by willgray** [comment]
oh - this works now with the resolution of this issue.  :)  @alexbaden was just asking if there was a place we could put the knowledge we gathered.  Right?

**Comment by alexbaden** [comment]
Yes.

**Comment by jovo** [comment]
maybe to ndstore docs?
not sure.

On Mon, Jun 20, 2016 at 10:01 PM, Alex Baden <notifications@github.com>
wrote:

> Yes.
>
> On Mon, Jun 20, 2016 at 7:21 PM William Gray <notifications@github.com>
> wrote:
>
> > oh - this works now with the resolution of this issue. :) @alexbaden
> > <https://github.com/alexbaden> was just asking if there was a place we
> > could put the knowledge we gathered. Right?
> >
> > —
> > You are receiving this because you were mentioned.
> >
> > Reply to this email directly, view it on GitHub
> > <https://github.com/neurodata/ndstore/issues/292#issuecomment-227315758
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AFkzUkS-k1OSwlk5hUY0ai1JApPH2mrDks5qNzyRgaJpZM4I39B9
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurodata/ndstore/issues/292#issuecomment-227320916>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACjcmIgH11wuKvCmnBy5zACmNjPqJxaks5qN0X2gaJpZM4I39B9>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
