### ISSUE TITLE
Ingest RGB data

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndstore#294]
I have RGB data that I would like to ingest.

Red Directory
- RedSlice_001.tif

  ...

- RedSlice_150.tif

Green Directory
- GreenSlice_001.tif

  ...

- GreenSlice_150.tif

Blue Directory
- BlueSlice_001.tif

  ...

- BlueSlice_150.tif

@Aeusman @kunallillaney how would I do this?

**Comment by Aeusman** [comment]
Do you want it as separate channels? As in, do you want to view the RGB colors together or as separate channels each for red, blue, green?

**Comment by kkutten1** [comment]
No I want them combined into a singe RGBA image so that I can visualize them.  

@alexbaden: Can ndviz display RGBA images?

**Comment by alexbaden** [comment]
ndviz can display anything that ndstore can render into a tile.

**Comment by kunallillaney** [comment]
@kkutten1 There are 2 ways ndstore can handle this data:

1. You can ingest this into a single channel called RGB uint32 which will render a RGB tile(ndviz can display this). 
2. You can ingest this data into 3 8-bit channels which will be rendered as Greyscale. I guess that ndviz cannot combine this data into RGB data for visualization(@alexbaden can confirm?).

The reason to choose one over the other is for analysis purposes. In the past, some people have chosen to ingest their RGB data as 3 separate channels(eva and boyden group) while some have chose to ingest them as a single uint32 channel(mitra and others). You have to decide what makes sense for your analysis and purposes.
If you choose option 1 then the data you have is in the incorrect format and you will have to combine your images into a single RGB image before ingesting. If you choose option 2 even then the data is still in the incorrect format but only mildly so(different file names) and @Aeusman can help you rename them using a simple command.

**Comment by alexbaden** [comment]
That's correct. But, if you ingested into three 8-bit channels, ndviz could
display all three and false color each appropriately.

We've also never tested ndviz on RGB / uint32 data that isn't annotation
data -- so while it theoretically should work, I bet there are bugs.

Why not try ingesting one slice in each of the formats and seeing which
works best?

**Comment by kkutten1** [comment]
OK I see what you're saying.  So If I don't want to use alpha transparency, should I set the 4th byte in the 32-bit RGBA data to 255?

**Comment by kunallillaney** [comment]
Yes.

**Comment by Aeusman** [comment]
@kkutten1 
Ingesting Docs: http://docs.neurodata.io/ndstore/sphinx/ingesting.html
Naming Conventions/Data Model: http://docs.neurodata.io/ndstore/sphinx/datamodel.html
Rename Command: http://askubuntu.com/questions/58546/how-to-easily-rename-files-using-command-line

**Comment by kkutten1** [comment]
So I notice that I need to specify a data_url in the autoingest script.  But I have data stored on a disk. Is there a way to use this script on a local directory? 

https://github.com/neurodata/ndstore/blob/master/ingest/autoingest/autoingest.py

**Comment by Aeusman** [comment]
Not at the moment, in a few weeks or months time, yes, but for now the answer is no.

**Comment by kunallillaney** [comment]
@kkutten1 close this when you get the data ingested.

**Comment by kkutten1** [comment]
Will do

**Comment by kunallillaney** [comment]
@kkutten1  Can we close this?

**Comment by kkutten1** [comment]
No.  Still need to do this but was busy with other things.

**Comment by kkutten1** [comment]
Closing because I've ingested the data.  Thanks everyone for your help.
