### ISSUE TITLE
http://openconnecto.me/ocp/ca/public_tokens 

### ISSUE THREAD

**Issue by jovo** [neurodata/ndstore#300]
8:35PM EDT, from annapolis, md.

http://openconnecto.me/ocp/ca/public_tokens never resolves.
same for http://console.neurodata.io/

happy to provide more info if desired, please instruct...

(of note, i'm trying to determine whether a particular dataset is public.)

**Comment by kunallillaney** [comment]
Both resolve for me and work. @jovo Can you check again?

**Comment by jovo** [comment]
fixed!

On Mon, Jul 4, 2016 at 11:26 PM, Kunal Lillaney <notifications@github.com>
wrote:

> Both resolve for me and work. @jovo <https://github.com/jovo> Can you
> check again?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurodata/ndstore/issues/300#issuecomment-230380627>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACjcphSzy9r1pw8GSRCzBeFjns5fKeLks5qSc72gaJpZM4JEs7l>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
