### ISSUE TITLE
Validate ndio performance

### ISSUE THREAD

**Issue by wrgr** [neurodata/ndstore#301]
We've made a bunch of good updates to make ndio work better with ndstore.  This includes greatly reducing proj info queries, better chunking sizes, unified calls through get_cutout, better cube alignment, etc.

Have build a very basic timing script; local time from request to numpy array in memory is about 30 seconds for 100MB of cube aligned data (same with and without chunking, finally!).  Thoughts on how we can go faster?  Or is this expected?  When chunking, our block sizes are 1024x1024x16.

https://gist.github.com/willgray/c35ffe5ea0fbe62e61a6c6ac95eb325d

**Comment by kunallillaney** [comment]
I am closing this since ndio is now defunct for all practical purposes.
