### ISSUE TITLE
JPEG Stack Service for (Py)KNOSSOS: (near-) isotropic stacks

### ISSUE THREAD

**Issue by adwanner** [neurodata/ndstore#304]
Is there a  way to retrieve (near-) isotropic jpeg stacks? This would be highly valuable for interfacing between ocp and [PyKnossos](https://github.com/adwanner/PyKNOSSOS) and other Knossos-like viewers that rely on cubed multi-resolution stacks.

Example: Assume an EM stack with native resolution (X=10,Y=10,Z=25)
Currently, the jpeg stacks would have the following voxel scales/sizes:
mag 0:  (X=10,Y=10,Z=25)
mag 1:  (X=20,Y=20,Z=25)
mag 2:  (X=40,Y=40,Z=25)
mag 3:  (X=80,Y=80,Z=25)
mag 4:  (X=160,Y=160,Z=25)
etc.

At low zoom levels, this is suboptimal. Therefore it would be desirable if one would receive the jpeg stacks with 
Option 1: (near-) isotropic scales (compatible with PyKnossos):
mag 0:  (X=10,Y=10,Z=25)
mag 1:  (X=20,Y=20,Z=25)
mag 2:  (X=40,Y=40,Z=40)
mag 3:  (X=80,Y=80,Z=80)
mag 4:  (X=160,Y=160,Z=160)
etc.
Option 2: constant factor scaling (compatible with PyKnossos and Knossos):
mag 0:  (X=10,Y=10,Z=25)
mag 1:  (X=20,Y=20,Z=50)
mag 2:  (X=40,Y=40,Z=100)
mag 3:  (X=80,Y=80,Z=200)
mag 4:  (X=160,Y=160,Z=400)
etc.

Personally, I would prefer option 1...

**Comment by kunallillaney** [comment]
@adwanner There is no current way to retrieve near-isotropic data in JPEG format. We do store both isotropic and near-isotropic data for some of our datasets. You can also ingest data in isotropic format by specifying so when you ingest the data. Two public datasets which support near-isotropic data are kasthuri11 and bock11. You can checkout kasthuri11 dimensions [here](http://openconnecto.me/ocp/ca/kasthuri11/info/).
This data can currently only be accessed by [Data API's](http://docs.neurodata.io/ndstore/api/data_api.html#get). Just append a neariso or iso to the URL. An example URL: http://openconnecto.me/ocp/ca/kasthuri11/image/npz/3/400,500/200,300/20,40/neariso/

If you would like to have one for JPEG format, feel free to open a PR and we will integrate it with our code. Or open an issue requesting this feature and we will get to it in the neat future.

**Comment by adwanner** [comment]
In fact, it seems there is already a way to retrieve near-isotropic data in JPEG format:
 http://openconnecto.me/ocp/ca/kasthuri11/image/jpeg/5/372,500/500,628/128,256/neariso/
The endpoint /neariso/ works just fine for jpeg.

**Comment by kunallillaney** [comment]
@adwanner Great. Then I might have added it but don't remember it now. Let me know if it works as expected. I wrote this service over a hackathon in which some KNOSSOS folks were present but we never had any indicator that it was being used.
