### ISSUE TITLE
extraction of partial overlapping subvolumes

### ISSUE THREAD

**Issue by adwanner** [neurodata/ndstore#305]
Let's assume I would like to cut out subvolumes of 128x128x128 voxels from a dataset with size 168x208x142 voxels (e.g. kasthur11, at magnification 7).
I can extract subvolumes, that are fully overlapping with the dataset, for example: 
GET http://openconnecto.me/ocp/ca/kasthuri11/image/jpeg/7/000,128/000,128/001,129/neariso/

However, I cannot extract any subvolumes that are only partially overlapping with the dataset, e.g.:
http://openconnecto.me/ocp/ca/kasthuri11/image/jpeg/7/128,256/000,128/001,129/neariso/
http://openconnecto.me/ocp/ca/kasthuri11/image/jpeg/7/128,256/128,256/001,129/neariso/

This would necessary in order to extract 128x128x128 JPEG stacks for (Py)KNOSSOS at the borders of a dataset.

**Comment by adwanner** [comment]
Context: I am currently working on an interface to ocp from [PyKnossos](https://github.com/adwanner/PyKNOSSOS) (the little python brother of Knossos) which is especially well suited for neurite tracing in (near-)isotropic datasets.

**Comment by kunallillaney** [comment]
The dimensions of the image at res7 are 168,208,1850(You can look at the dims by using the info query).  When you make a request for [128,256] in the x-dimension you are going out of bounds and that query will not work.  The queries you should be using are:
http://openconnecto.me/ocp/ca/kasthuri11/image/jpeg/7/128,168/000,128/001,129/neariso/
http://openconnecto.me/ocp/ca/kasthuri11/image/jpeg/7/128,168/128,208/001,129/neariso/

To answer in short, is that we do not pad our cutouts to meet multiples of 128,128,128. It is important to note that  if you want to efficiently use the system then your queries in general should be multiples of 128,128,16 in x,y,z dimension. So 128,128,128 queries being done by KNOSSOS work fine.

**Comment by kunallillaney** [comment]
@adwanner Great to hear about PyKNOSSOS. We did have someone from [scalable minds](https://github.com/scalableminds) who contributed a service called RAW which downloads a 3D/4D region of data for of a specified channel, resolution and bounds in a web readable raw binary representation numpy array format. 
Currently this service lives on the dev branch but will be rolled out soon. Are you aware of this?
Also, one question we had was how does KNOSSOS or PyKNOSSOS deal with the annotation data generated? We also store annotations in ndstore which can be written and read via RESTful services.

**Comment by adwanner** [comment]
@kunallillaney Thanks for the detailed answer. The JPEG cutout service does currently not work if  xdim != ydim (see [issue 275](https://github.com/neurodata/ndstore/issues/275)). It would be great if you could fix that such that I could use queries like
http://openconnecto.me/ocp/ca/kasthuri11/image/jpeg/7/128,168/000,128/001,129/neariso/

Regarding annotation data: PyKnossos is mainly file system based, but I am planning to incorporate ndstore and catmaid support these days.

**Comment by kunallillaney** [comment]
@adwanner When you say incorporate, do you mean to enable PyKnossos to read data from these stores or also write data back to them? What format do you use to store annotations on the file-system?

**Comment by adwanner** [comment]
The first step would be to enable PyKnossos to read data, the second would be to also write data back. Currently, the annotation objects are saved in the nml format of Knossos which is based on XML. Because PyKnossos is currently only used for skeleton tracing and synapse annotation, all PyKnossos annotation objects consist of nodes with attributes and edges that connect pairs of nodes.

**Comment by kunallillaney** [comment]
@adwanner Sounds awesome! Someone will help you ingest the skeleton data in ndstore and we can take it from there.
