### ISSUE TITLE
Datasets/Projects and timesteps

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndstore#306]
Do all timeseries projects and channels associated with a given dataset need to have the exact same number of timesteps as the dataset was declared with? I.e. if I have a set of images with the same physical dimensions but their time-lengths vary, could I create a "standard dataset" with a very large number of timesteps and then upload data with fewer timepoints to a project associated with it?

The motivation for this question is that in MR we would ideally like the following architecture:
- Dataset: Standard Space
  - Project: Study1
    - Channel: Subject i scan1 (with T timesteps)
    - Channel: Subject i scan2 (with D timesteps)
    - Channel: Subject i scan3 (with 1 timestep)
    - ...
  - Project: Study2
    - Channel: Subject j scan1 (with T' timesteps)
    - Channel: Subject j scan2 (with D' timesteps)
    - Channel: Subject j scan3 (with 1 timestep)
    - ...
  - ...

**Comment by kunallillaney** [comment]
No. They can be variable.
