### ISSUE TITLE
zmin and zmax scaling in getBoundingBox

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#308]
When the user requests a bounding box for an annotation at a resolution different from the default, the bounding box is obtained for the default channel resolution then scaled. However, I think the z-indices shouldn't be scaled because downsampling only happens in x and y.

(see: https://github.com/neurodata/spdb/blob/master/spatialdb.py#L881)

Removing the scaling from 881 and 884 fixed the bounds issues I was seeing. Let me know if this is actually a bug and I'll commit the change. 

( @kunallillaney )

**Comment by kunallillaney** [comment]
@alexbaden There is scaling in z for isotropic and near-isotropic data. The way we calculate scaling there is incorrect as it is generalized for x and y which is always 2. I think we need to have a separate scaling for z which is a factor of z-slices in the respective resolutions. @randalburns Does this sound right?

**Comment by alexbaden** [comment]
Following in the same vein, the `cubedim` setting in line 877 should be the cube dimension of the `effectiveres`, not the `resolution`: https://github.com/neurodata/spdb/blob/master/spatialdb.py#L877

**Comment by kunallillaney** [comment]
@alexbaden I will talk to @randalburns tomorrow about this. Can you please post a sample query here for reference?

**Comment by alexbaden** [comment]
Sure. I think I got it working. I'll commit the script I'm using to the
examples dir later this afternoon.

**Comment by randalburns** [comment]
Is done and committed into the allen branch of spdb.  Didn't want to commit to spdb.  Kunal want to merge?  I'm assigning to you.

**Comment by kunallillaney** [comment]
I do not see any new commits to the spdb repo. There were some changes in the allen branch in April which have merged quite some time back. Was that it?
