### ISSUE TITLE
Docs Changes

### ISSUE THREAD

**Issue by Aeusman** [neurodata/ndstore#315]
These are docs changes that need to occur for microns, documenting here.
- [x] Link to install information for ndio in Sphinx docs(line89). Look at ingesting.rst to see how I reference hyperlinks in RST's.
- [x] Tell them about channel names and how we name them - This is already documented in the data model.
- [x] Create a autoingest_complicated or advanced(don't care about the name). I want everything necessary removed from existing autoingest.py. Just the basic options for the user. The advanced version can have the current version of autoingest.
- [x] Better explanation in the overview. Make it clear that dataset and project are for back-end use. The user interacts with token and channel only. Add this to the data model.
- [x] Add common mistake on x, y swap. Make it clear what x and y are and how to identify them Maybe use identify on the command line
- [x]  FAQ: You can download sub volumes of data using our RESTful API's. Here is the documentation for this. You catch fetch the data in HDF5, Numpy or Blosc format. I highly recommend fetching this data in regions of 1024,1024,16. You can also use our python library NDIO which wraps around these RESTful API's. 
- [x]  Resolution definition: To answer your questions: We build a multi-resolution hierarchy for each project where each higher resolution is scaled down by a factor of 2 in the x and y dimensions(the number of z slices remain the same). You can access all project metadata via RESTful calls( documentation - http://docs.neurodata.io/ndstore/api/info_api.html). I am not sure what the function name in NDIO is that performs this RESTful call(asking them in a git issue will help).
- [x] https://github.com/neurodata/ndstore/issues/306
- [x] https://github.com/neurodata/ndstore/issues/305
- [x] https://github.com/neurodata/ndstore/issues/304
- [x] https://github.com/neurodata/ndstore/issues/272
- [x] https://github.com/neurodata/ndstore/issues/257 - deprecated by viz
- [x] Data may not be present on first slice

**Comment by Aeusman** [comment]
@kunallillaney Tag anything else as needed please

**Comment by kunallillaney** [comment]
- [ ] #319

**Comment by kunallillaney** [comment]
@Aeusman What is the status of these? Let's wrap this soon so we can push these out.

**Comment by Aeusman** [comment]
why is #257 here?

**Comment by kunallillaney** [comment]
@Aeusman Just tell them that they can do this in NDViz and direct them to the docs there.

**Comment by kunallillaney** [comment]
@Aeusman Let's wrap the last few of these and close this issue.

**Comment by kunallillaney** [comment]
Done.
