### ISSUE TITLE
Delete Channel in GUI Fails

### ISSUE THREAD

**Issue by Aeusman** [neurodata/ndstore#319]
While delete channel 'image' from project 'allen_gold_16_zebrafish_larve_RGC_UW_hard_1_1_Live_2_2_2010_9_52_24_AM_med_Red_tif_uint8'

Environment:

Request Method: POST
Request URL: http://openconnecto.me/ocp/ocp/ocpuser/channels/

Django Version: 1.8.4
Python Version: 2.7.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'ocpca',
 'overlay',
 'synaptogram',
 'catmaid',
 'registration',
 'ocpuser',
 'djcelery',
 'ocpviz',
 'stats',
 'corsheaders')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')

Traceback:
File "/usr/share/ocp/virtualenvs/ocp/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/share/ocp/virtualenvs/ocp/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "./ocpuser/views.py" in getChannels
  324.             pd.deleteOCPCAChannel(pr, ch.channel_name)
File "/usr/share/ocp/open-connectome/ocpca/ocpcaproj.py" in deleteOCPCAChannel
  570.           conn.rollback()

Exception Type: UnboundLocalError at /ocp/ocpuser/channels/
Exception Value: local variable 'conn' referenced before assignment

**Comment by Aeusman** [comment]
@kunallillaney

**Comment by kunallillaney** [comment]
Project and Channel names are governed by the rules of the underlying storage engine, in this case MySQL. You cannot create a project name more than 64 characters long. I would stick to 20-25 chars max. More information [here](http://www.informit.com/articles/article.aspx?p=30875)
