### ISSUE TITLE
ndio doesn't fail if a channel is created and the underlying tables exist

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#323]
E.g., I create the channel `test` using the console. I then delete `test`, but the delete fails and a table still remains. I then re-create `test` using ndio. The creation should fail, because the channel creation fails (e.g. `Failed to create channel. "Failed to create tables for new project 1050: Table 'test_ramon' already exists."`) but it doesn't.

Documenting here because the ndio error checking is pretty well implemented for create_channel. Pretty sure it's a problem on the ndstore end...

**Comment by kunallillaney** [comment]
Which branch is this and what kvengine?

**Comment by alexbaden** [comment]
microns / mysql

**Comment by alexbaden** [comment]
The point of this issue is if channel creation fails in the ndstore web console, it should also fail in the create channel JSON endpoint, which it currently doesn't seem to.

**Comment by kunallillaney** [comment]
can you give me sample call which ndio is making which seems to succeed.

**Comment by kunallillaney** [comment]
For the record, the issue was in NDIO but the backend now should work.
