### ISSUE TITLE
correct voxel res 

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#326]
- [x] kharris\* --> 2 x 2 x 50
- [x] bock11 --> 4 x 4 x 40 
- [x] kasthuri11 --> 4 x 4 x 40
- [x] clarity @kkutten1 to provide list 
- [ ] AT data @alexbaden to find out
- [ ] others??

**Comment by kkutten1** [comment]
@alexbaden: See https://github.com/neurodata/internal/blob/master/misc/CLARITY_tokens.md

**Comment by alexbaden** [comment]
- [ ] collman14: 
- [ ] collman15:
- [ ] weiler14:
- [ ] kristina15:

**Comment by kkutten1** [comment]
I want to change the resolution of the CLARITY datasets to their correct values.  For example I want to change the resolution of the Control258 dataset from 1 x 1 x 10 nm to its correct value of 585 x 585 x 5000 nm.  When click the "Update Dataset" button in the admin console I get the following warning

_WARNING Editing some fields may be dangerous!! Specifically, if you change the scaling option or **voxel resolution**, you may render existing data unusable. The physical layout of the databases depends upon these factors. **It is generally safe to change the voxel resolution in minor ways or if you keep the ratio of values the same.** If you change the image size or start/end time, you may have existing data that you can no longer access. It is safe to change all fields if you have not created projects that use this dataset._

Could I make this change without breaking anything? The ratios of the correct values are _similar_ but not the _same_ as the old ones. I think @randalburns said that this would be OK.  But I'm checking to be sure.

**Comment by alexbaden** [comment]
Yes. 

Well, maybe. If you change the ratio between the xy resolution and the z resolution, you could break something. But it isn't permanent (unless you change the ratio then re-propagate). 

So, go ahead and update the datasets for which you have access. If you don't have access to a particular dataset, let me know and I'll update it for you.

**Comment by kkutten1** [comment]
@alexbaden:  It won't let me make the changes.  When I tried I following error:

_Cannot update. You are not owner of this dataset or not superuser._

Could you change the resolution to  Control258 for me?  It should be 585 x 585 x 5000 nm.  This one is the most important since I'm using it as an example in a tutorial I'm writing.  If you have time could you also change the resolutions of the other brains [listed here](https://github.com/neurodata/internal/blob/master/misc/CLARITY_tokens.md)?  Their resolutions are listed in um so you'll have to multiply them by 1,000 to get the correct spacing in nm.

**Comment by kunallillaney** [comment]
@kkutten1 Hey I have updated the voxelres for all CLARITY datasets to 585,585,5000. Let me know if you have any questions on this.
@alexbaden AT data issue is still open and is tasked to you. @randalburns said to close this issue and you can move that to your weeklies.
@jovo

**Comment by alexbaden** [comment]
Please move it for me or I will forgot.

**Comment by jovo** [comment]
https://github.com/neurodata/ndstore/issues/376

**Comment by kkutten1** [comment]
@kunallillaney: Some of the CLARITY brains have different resolutions.  For example Control181 is 585 x 585 x **8000** nm.  See https://github.com/neurodata/internal/blob/master/misc/CLARITY_tokens.md
Could you change those? Thanks

**Comment by kunallillaney** [comment]
@kkutten1 All done.
