### ISSUE TITLE
document json ramon interface

### ISSUE THREAD

**Issue by randalburns** [neurodata/ndstore#334]
http://localhost:8000/ramon/test/anno/query/ann_type/2/
http://localhost:8000/ramon/test/anno/2/boundingbox/0/
http://localhost:8000/ramon/test/anno/topkeys/10/type/2/

**Comment by alexbaden** [comment]
Done and pushed to microns. 

Available here: http://brainviz1.cs.jhu.edu/doc/ndstore/api/ramon_api.html
