### ISSUE TITLE
can't run unit tests

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#339]
```
test_time.py:24: in <module>
    import makeunitdb
makeunitdb.py:22: in <module>
    application = get_wsgi_application()
/home/ubuntu/.virtualenvs/nd/local/lib/python2.7/site-packages/django/core/wsgi.py:14: in get_wsgi_application
    django.setup()
/home/ubuntu/.virtualenvs/nd/local/lib/python2.7/site-packages/django/__init__.py:18: in setup
    apps.populate(settings.INSTALLED_APPS)
/home/ubuntu/.virtualenvs/nd/local/lib/python2.7/site-packages/django/apps/registry.py:78: in populate
    raise RuntimeError("populate() isn't reentrant")
E   RuntimeError: populate() isn't reentrant
```

Anyone seen this before?

@kunallillaney @Aeusman @randalburns

**Comment by kunallillaney** [comment]
I am not aware of this bug. We were able to run the tests minus the celery ones because there is an issue with django-celery and django-1.10. Try removing the ramon app and check again. Seems like a bug introduced by recent commits.

**Comment by alexbaden** [comment]
I fixed it, I think. It turns out the file `ramon.py` in the test directory conflicts with the new `ramon` app. I renamed `ramon.py` to `ramonmethods.py` in the test directory **AND** deleted the `ramon.pyc` file and it worked. Similar experience to anyone running the latest microns?

**Comment by alexbaden** [comment]
Note that if you can't reproduce this bug before pulling the commit referenced above, trying adding `ramon` to your list of INSTALLED_APPLICATIONS in `settings.py`.
