### ISSUE TITLE
Issue with Histogram Migrations in django1.10

### ISSUE THREAD

**Issue by kunallillaney** [neurodata/ndstore#357]
I get this error when I try to generate or apply migrations:
Model class stats.models.Histogram doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS

**Comment by kunallillaney** [comment]
@alexbaden Part of this might be an outdated setting with me. Let me check

**Comment by alexbaden** [comment]
Is "stats" in your INSTALLED_APPS list in settings.py?

**Comment by kunallillaney** [comment]
that solved part of the issue. The other issue was that some conflict in the migrations themselves. I had to merge migrations before applying them. I have now pushed this.

**Comment by alexbaden** [comment]
Ok, thanks. I'll take a look. I took the stats migrations out of nduser and
moved them to stats, which probably caused the problem. But in the future,
nduser migrations won't conflict with stats.
