### ISSUE TITLE
console not recognizing logged in user 

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#365]
steps to reproduce:

- install ndstore on aws 
- create superuser 
- head on over to `<<aws instance url>>/nd/nduser/profile/`
- logging in works fine,  but once logged in the header doesn't seem to detect a user is logged in (see screenshot) 

<img width="1454" alt="screen shot 2016-09-03 at 10 22 39 am" src="https://cloud.githubusercontent.com/assets/5845842/18226126/5d4fb678-71c0-11e6-9caa-31f48e87c373.png">

I'll investigate as well, but I was wondering if this had anything to do with laying the groundwork for auth, or maybe a django 1.10 issue?

**Comment by alexbaden** [comment]
Reproduced locally. I'm looking into this now.

**Comment by kunallillaney** [comment]
@Aeusman Merge these branches locally and confirm if I can merge your pull request.
