### ISSUE TITLE
catmaid interface on aws times out / doesn't load 

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#368]
http://52.91.174.4/ocp/catmaid/kasthuri11/image/xy/1/0_1_7.png

**Comment by kunallillaney** [comment]
You are using the incorrect IP:
http://52.91.173.4/nd/catmaid/kasthuri11/image/xy/5/0_0_1.png

There is another issue with this which was introduced by @randalburns. He and I need to talk to fix this.
