### ISSUE TITLE
Propagate connection refused error

### ISSUE THREAD

**Issue by alee156** [neurodata/ndstore#373]
OSX operating system, Chrome/Safari browser

When I try to propagate Ailey's new brains by typing in the following url -
openconnecto.me/ocp/ca/my_token/my_channel/setPropagate/
(Token and Channel hidden since her brains are private)

I get a connection refused error - I'm almost 100% sure this is because I got the server name incorrect/I'm doing wrong but I'd really appreciate the help!

Thanks

**Comment by kunallillaney** [comment]
openconnecto.me/ocp/ca/my_token/my_channel/setPropagate/propagate-value

What is your propagate value?

**Comment by kunallillaney** [comment]
@alee156 Is this resolved?

**Comment by alee156** [comment]
I get a page not found 404

**Comment by kunallillaney** [comment]
@alee156 That is the HTTP response code and not what I am referring to. I think you are not using the RESTful correctly. Can you please mention the actual RESTful call you use to call this service because the one you mention is **incomplete**.

**Comment by Aeusman** [comment]
@alee156 Were you able to propagate the images using a proper propagate-value?

**Comment by alee156** [comment]
Nope

**Comment by kunallillaney** [comment]
@alee156 Use this:
openconnecto.me/ocp/ca/my_token/my_channel/setPropagate/1/
