### ISSUE TITLE
imgUpload throwing "NameError: global name 'datasetSize' is not defined"

### ISSUE THREAD

**Issue by toekneesunshine** [neurodata/ndstore#375]
I'm trying to ingest a histogram equalized version of the CLARITY brain Aut1367 into ndstore.  Since the Aut1367 data already exists in ndstore, I downloaded the image and then applied our histogram equalization technique.  The technique outputs a numpy array, which I then convert into a simpleITK image (following the last steps in the ndreg tutorial, whereby they upload a simpleITK img: https://github.com/neurodata/ndreg/blob/master/doc/3D_CLARITY_RegistrationAndAnalysis.ipynb).

I then created an OpenConnectome account and made a private dataset called "Aut1367_histeq", with token as "Aut1367_tony" and channel as "histogram_equalization".  I set the X image size, Y image size, Z image size on my ndstore dataset to the values I got from the image dimensions.  However, when I call imgUpload as follows:

token = "Aut1367_tony"
channel = "histogram_equalization"
imgUpload(Aut1367_histeq_ITK, token, channel)

I get a "NameError: global name 'datasetSize' is not defined".

Am I missing something?  Is there a way for me to efficiently upload these histogram equalized ITK snap images with imgUpload?

**Comment by kunallillaney** [comment]
@toekneesunshine I need more details. Which server are you running this on? Also, have you verified if this an ndio issue or not? I need the RESTful call this is making to debug this not the function you are calling in ndio.

**Comment by kunallillaney** [comment]
@toekneesunshine Any updates?
@jovo

**Comment by toekneesunshine** [comment]
@kunallillaney 
The raw data is on a GoogleCloud instance.
After looking through the error message, it seems to more likely be a problem with one of the ndreg functions (specifically, this imgUpload function) -- I'll make an issue there instead.

**Comment by kunallillaney** [comment]
Okay. Closing the issue then.
@jovo
