### ISSUE TITLE
kasthuri11cc res0 and neariso missing

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#378]
Res0 table is empty

neariso tables missing for res4, 5, 6, 7

@randalburns

**Comment by kunallillaney** [comment]
kat11cc never had res0 or neariso data. katthuri11cc only ran at base res1. Similarly, we only generated neariso tables for kasthuri11 not kasthuri11cc.

**Comment by wrgr** [comment]
Res0 definitely exists.  Maybe needs to be re exported.

**Comment by kunallillaney** [comment]
@wrgr res0 for kasthuri11 exists not for kasthuri11cc. If I remember correctly, Misha only ran the algorithm on res1 and we propagated it upwards. I went and rechecked the SQL backups we have for this data and there is no res0.
Similarly, @randalburns only generated neariso versions for kasthuri11 for Stephan and not on kasthuri11cc.
