### ISSUE TITLE
Programmatically creating channels in ndstore

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndstore#380]
I am trying to programmatically create channels through the RESTful API. I have followed the documentation [here](http://docs.neurodata.io/ndstore/api/json_api.html#createchannel) in creating my url and json file. I have produced a [script](http://openconnecto.me/mrdata/share/ingest/brains/createchannel.py) (taking the structure of [putnifti.py](https://github.com/neurodata/ndstore/blob/master/examples/putnifti.py) and the restful post call from [restutil.py](https://github.com/neurodata/ndlib/blob/master/restutil.py#L88)) and a [json file](http://openconnecto.me/mrdata/share/ingest/brains/request.json) (copying the documented example directly).

Calling my script produces the following result:
```
$ python createchannel.py mri.neurodata.io gktest1 request.json
http://mri.neurodata.io/nd/ca/gktest1/createChannel/
success
```

However, despite no error being raised in the post, there is no new channel, as can be seen [here](http://mri.neurodata.io/nd/ca/gktest1/info/).

Note: @kunallillaney is working on a script to solve this problem now and will comment here once completed. 😄 

@jovo @randalburns @kunallillaney

**Comment by kunallillaney** [comment]
The script is [here](https://github.com/neurodata/ndstore/blob/microns/examples/createchannel.py).
Example usage: `python createchannel.py KKI2009_aligned kki2009 test image uint8`
This creates a channel name "test" of type "image" and datatype "uint8".
