### ISSUE TITLE
RESTful call to set window

### ISSUE THREAD

**Issue by randalburns** [neurodata/ndstore#381]
This is for kwame to set ranges on CLARITY brains.

**Comment by kunallillaney** [comment]
@randalburns This is done in the resource interface. You can now update any parameter for any metadata(channel, project, token or dataset) using the resource interface.
Caveat: This only works in the current "microns" branch and is not fully documented.

**Comment by kunallillaney** [comment]
TODO for me: Document the resource service.

**Comment by kunallillaney** [comment]
Documented in the resource api.
