### ISSUE TITLE
Propagate appears to be frozen

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndstore#382]
I initialized propagate a week ago on a  1140 x 800 x 1320 voxel channel using
```
http://openconnecto.me/ocp/ca/AutA_to_ara3/grayscale/setPropagate/1/
```
But as of today the propagate still isn't finished. The following returns a value of "1"
```
http://openconnecto.me/ocp/ca/AutA_to_ara3/grayscale/getPropagate/
```
@randalburns @kunallillaney @jovo

**Comment by kunallillaney** [comment]
@kkutten1 It is fixed and here is the data at res1.
http://dsp029.pha.jhu.edu/ocp/ca/AutA_to_ara3/grayscale/xy/1/0,500/0,400/1/
