### ISSUE TITLE
make account creation work

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndstore#386]
I am trying to create an account on [cloud.neurodata.io/nd/accounts/login/](http://cloud.neurodata.io/nd/accounts/login/) and recieved the following confirmation email.

>Welcome to NeuroData!
> To finalize your account, just visit the address below. (If it's not a link, you can copy and paste it into your web browser's address bar.)
>http://example.com/nd/accounts/activate/53e747cbf578742244ab072ac669cdaff900b944/
>If you didn't sign up for an account, just ignore this message:

The link within this email did not activate my account and therefore I could not login and use your service.

(I know the administrator login, but the whole point is that an external user is currently not able to use the service without us giving them our password, which seems like a bad thing)

**Comment by gkiar** [comment]
I believe this should be a trivial amount of work, as when I replace `example.com` with `cloud.neurodata.io` I am able to activate my account successfully.

**Comment by kunallillaney** [comment]
@gkiar cloud.neurodata.io is off-limits and is under beta. Please do not create accounts/tokens on it until I say so. You are free to read data off it but I cannot guarantee uptime or any tokens you create will be carried over.
Having said that, yes that is the issue and I think @Aeusman was working on registration last. I will co-ordinate with him and get this fixed.

**Comment by gkiar** [comment]
Thank you.

Where do you suggest I test, then? I am not storing any unique (or even large) datasets, but rather am trying to test our service as if I were an outside user.

**Comment by gkiar** [comment]
I view what I am doing as "beta testing," so perhaps upon clarification of my goal this is the right instance for this, but please do let me know :)

**Comment by kunallillaney** [comment]
@gkiar This is great. Just delete all datasets/projects/tokens you have created after you are done. Also, please don't upload any new data for now. You can beta-test the GUI which is what we need. Some other services aka propagate, stats don't run in the cloud yet.

**Comment by kunallillaney** [comment]
@gkiar This is resolved now.

@Aeusman @randalburns django by default inserts example.com as the site name when it creates the project. One can modify this manually by using the sites-admin interface. The automated way to do this is to use migrations(django recommends this and not fixtures. django1.7> they moved away from having this as a parameter in the settings file) I wrote a migration in fixtures.migrations which cleans out the django_sites table and inserts cloud.neurodata.io as the site_name. Currently this name is hard-coded in the migration file, we can find a way to load this from custom settings variable at a later stage.
