### ISSUE TITLE
Propagate may be frozen for Tail projects

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndstore#388]
I started propagate on both channels "ch0" and "ch1" more than 48 hours ago and both still have a propagate status of 1.  @kunallillaney: I've posted the project token in Slack

**Comment by kkutten1** [comment]
Interestingly lower resolutions appear to be available

http://openconnecto.me/ocp/ca/<TailToken>/ch0/xy/5/0,447/0,595/900/window/0,600/

Not sure why it's still reporting a status of "1"

**Comment by kunallillaney** [comment]
@kkutten1 resolved. Closing issue.
