### ISSUE TITLE
Voxel Resolution for Tail datasets are in microns instead of nanometers

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndstore#392]
I want to multiply the voxel resolution Tail datasets by 1000 so that they are in nanometers.  But I don't have access to them in the admin console. For consistency we should always enter the voxel resolution in  nanometers since that's what the admin console requests.  Like below
![screenshot1](https://cloud.githubusercontent.com/assets/9724840/21268663/a8d192a6-c37d-11e6-931d-70c6e975ff0e.png)

The 'voxelres' entries for the Tail dataset (MyToken1, MyToken2 and MyToken3) are 0.585 x 0.585 x 5.  They should be 585 x 585 x 5000.

http://openconnecto.me/ocp/ca/MyToken1/info/
http://openconnecto.me/ocp/ca/MyToken3/info/
http://openconnecto.me/ocp/ca/MyToken2/info/

**Comment by kunallillaney** [comment]
Done.
