### ISSUE TITLE
Can't connect to MySQL server on 'dsp061.pha.jhu.edu' 

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndstore#396]
I receive the following error 
```
(2003, "Can't connect to MySQL server on 'dsp061.pha.jhu.edu' (111)")
```
...when trying to download slice of image data

http://openconnecto.me/ocp/ca/[MyToken]/grayscale2/xy/0/0,100/0,100/15/

**Comment by kunallillaney** [comment]
Done.
