### ISSUE TITLE
Need to restart propagate on Talia brain

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndstore#397]
Propagate for one of the channels ("ch1") of [myToken] appears to have failed

http://openconnecto.me/ocp/ca/[myToken]/ch1/xz/1/3000,4000/7000/0,1000/window/0,600/

It's propagate status has been "1" for at least a week

http://openconnecto.me/ocp/ca/[myToken]/ch1/getPropagate/

I don't have the permissions to restart propagate.  When I try to set it to "0" so that I can restart propagation....

http://openconnecto.me/ocp/ca/[myToken]/ch1/setPropagate/0/

I get the following error...
```
Cannot set this value. Project is under propagation.
```

**Comment by kunallillaney** [comment]
@kkutten1 I have restarted this.

**Comment by kunallillaney** [comment]
Propagated.
