### ISSUE TITLE
Propagation finishes sucessfully without setting status to "2"

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndstore#398]
Propagation for channel "ch0" of [myToken] appears to have been successful as all resolutions down to level 10 contain data

http://openconnecto.me/ocp/ca/[myToken]/ch0/xz/10/0,15/7/0,1000/window/0,600/

But the propagate status is still "1" and has been that way for at least a week

http://openconnecto.me/ocp/ca/[myToken]/ch0/getPropagate/

When I try to manually set it to "2" to indicate success...

http://openconnecto.me/ocp/ca/[myToken]/ch0/setPropagate/2/

... I receive the following error
```
Invalid Value 2 for setPropagate
```

**Comment by kunallillaney** [comment]
@kkutten1 This is resolved.
