### ISSUE TITLE
dsp061.pha.jhu.edu is down

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndstore#401]
@kunallillaney: dsp061.pha.jhu.edu is appears to be down. When trying to access an xy slice 
```
http://openconnecto.me/ocp/ca/ara_ccf3/average/xy/0/0,500/0,300/500/
```
The following error is returned
```
(2003, "Can't connect to MySQL server on 'dsp061.pha.jhu.edu' (111)")
```

**Comment by kunallillaney** [comment]
@kkutten1 There have been some hard-drive issues with DSP61 and we have lost all data on that drive. We did have backups for our important datasets but unfortunately not for that one. Was that Ailey's data?

**Comment by kkutten1** [comment]
No it's atlas data.  I have a backup on my hard drive so I can reingest it.

**Comment by kunallillaney** [comment]
@kkutten1 Great. I will let you know when these issues are resolved and we are ready to start ingesting. Also, do you have a list of Ailey's data that we care about?

**Comment by kkutten1** [comment]
@kunallillaney: Will send you a list of tokens on slack

**Comment by kunallillaney** [comment]
@kkutten1 I will close this since we discussed this issue
