### ISSUE TITLE
Missing annotation data?

### ISSUE THREAD

**Issue by wrgr** [neurodata/ndstore#407]
Seems like with the recent disk failure, several of the annotation data sets that were hosted on DSP061 are missing.  Can you help me confirm the current state of things and assess what is possible with recovery/existing backups?

Many thanks!

@kunallillaney @alexbaden @perlman @jovo @randalburns

**Comment by kunallillaney** [comment]
There are the annotation projects from dsp61 for which we have backups:
ac3
ac4
kasthuri14anno
kasthuri14Maine
kasthuri14s1colANNO
kat11greencylinder
kat11mojocylinder
kat11redcylinder
kat11mito
kat11synapses
kat11segments
kat11vesicles
kat14psd
katss
kat11redcylinder
kat11mojocylinder
MP4merged
rhoana
collman15anno
collman15axons
collamn15dendrites
collman15dendrites
kristen-harris annotations

**Comment by kunallillaney** [comment]
All other annotation data on DSP61 is unfortunately not recoverable. If you did take a backup or have local HDF5/tif files then we can re-ingest them.

**Comment by wrgr** [comment]
Yikes - any chance of data forensics or other options?  @jovo?  If really lost a pretty big loss.  Can chat offline if better.  Want to confirm we are really out of options.  Didn't expect to lose these projects.

**Comment by randalburns** [comment]
Question has been answered.  I'll communicate with Will offline.
