### ISSUE TITLE
make neariso generation a default part of propagate

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#410]
Per our conversation earlier -- the people like the neariso interface. We should generate those tables during propagate. (paraphrased from @randalburns)

The issue we're having right now is if the neariso table doesn't exist, the call to get data with the neariso interface in ndviz/neuroglancer fails. As a quick fix, we could exclude neariso from projinfo unless those tables exist, explicitly.

**Comment by kunallillaney** [comment]
See #415
