### ISSUE TITLE
niftii service: SWU4 and MRN114 broadcast array shapes

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndstore#439]

**Comment by randalburns** [comment]
@gkiar I'm not positive what this is.  I am closing b/c I can ingest SWU4 and MRN114.  Let me know when you have new data from updated pipeline versions.

**Comment by gkiar** [comment]
@randalburns, I think you asked me to open it last meeting when we chatted
about mricloud.

Also, all new data is processed and available at http://m2g.io

--
Greg Kiar <gkiar07@gmail.com>
