### ISSUE TITLE
Can not crerate channels of type "image" from dev.neurodata.io admin console

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndstore#445]
@perlman, @kunallillaney 

Steps to reproduce...

Log into dev.neurodata.io admin console
* "Projects"->"View Projects"
 * For project "myToken", click "channels" which will take you to the "CHANNELS" list page
 * Click "Add Channel", enter name "test_channel" for "Channel Name" and select "Images (16-bit unsigned)" for "Channel Type"
 * Click "Create Channel" and this will take you back to the "CHANNELS" list page
 * On the "CHANNELS" page "Channel Type" for "test_channel" will incorrectly say "timeseries" instead of "image"

Right now I'm working around this by using the ndio.remote.create_channel method.  I think @kunallillaney just needs to reapply the fix he described [here](https://github.com/neurodata/ndio/issues/273#issuecomment-286862369)

**Comment by kkutten1** [comment]
OK so some tokens e.g. (token, channel)=("ara3", "average") now have a channel type of "timeseries" although they were created as type "image"

**Comment by perlman** [comment]
All channels are now timeseries.  What was image data are now timeseries of 1.

@kunallillaney and I tried to migrate all of the old data on dev.neurodata.io.  If things are not working, the easiest path will probably be to create a new project.

**Comment by kkutten1** [comment]
Maybe we should close this since this is a feature (not a bug).  I've reuploaded the ARA
