### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by kunallillaney** [neurodata/ndstore#61]
1. Remove resolution and annotations from create channel page if the channel is not an annotation one. 
2. Add help/small pop up box for each field.
3. CSS - same as ocp.me

**Comment by kunallillaney** [comment]
@j6k4m8 I am updating a list of possible improvements #61 and #60 for Bugs. Look at them when you get a chance and add on.

**Comment by j6k4m8** [comment]
@Aeusman could you send me descriptions for what each of
<kbd>Project</kbd> <kbd>Description</kbd> <kbd>Public</kbd> <kbd>Dataset</kbd> <kbd>Database Host</kbd> <kbd>KV Engine</kbd> <kbd>KV Server</kbd> <kbd>Legacy Project?</kbd> <kbd>Link to existing database</kbd> <kbd>Create a default token</kbd> means, so I* can add them as quick blurbs? 

* Where "I" is some subset of { you | kunal | me }

**Comment by kunallillaney** [comment]
@Aeusman You did have a wiki FAQ page for this. I think that is a good place to start.
